name: Auto Preload ALL

on:
  push:
    branches: [ main ]

jobs:
  preload:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch file list (ONLY FILES)
        run: |
          curl -s https://api.github.com/repos/mehmednizam28/fastdl/git/trees/main?recursive=1 \
          | grep '"type": "blob"' -B 5 \
          | grep '"path"' \
          | cut -d '"' -f4 > files.txt

      - name: Filter csfiles
        run: |
          grep '^csfiles/' files.txt > filtered.txt || true

      - name: Preload cache
        run: |
          while read line; do
            if [ ! -z "$line" ]; then
              echo "Caching $line"
              curl -s https://https://csfastdl.mehmednizam28.workers.dev/$line > /dev/null
              sleep 0.05
            fi
          done < filtered.txt
