name: Warm Cloudflare Cache

on:
  push:
    branches: [ main ]

jobs:
  warm:
    runs-on: ubuntu-latest

    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get all files
        run: |
          curl -s https://api.github.com/repos/mehmednizam28/fastdl/git/trees/main?recursive=1 > tree.json

      - name: Extract file list
        run: |
          jq -r '.tree[] | select(.type=="blob") | .path' tree.json > files.txt

      - name: Warm Cloudflare cache
        run: |
          while read file; do
            echo "Warming $file"
            curl -s "https://csfastdl.mehmednizam28.workers.dev/" > /dev/null
            sleep 0.05
          done < files.txt
