name: Warmup FastDL Cache
on:
  push:
  workflow_dispatch:

jobs:
  warmup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Hit all files in csfiles
        run: |
          # Влизаме в папка csfiles и обхождаме всичко вътре
          cd csfiles
          find . -type f \( -name "*.bsp" -o -name "*.mdl" -o -name "*.wav" -o -name "*.spr" -o -name "*.wad" \) | while read file; do
            # Махаме точката отпред (./map.bsp -> map.bsp)
            CLEAN_PATH=$(echo $file | sed 's|^\./||')
            URL="https://csfastdl.mehmednizam28.workers.dev/$CLEAN_PATH"
            echo "Warming up: $URL"
            curl -s -L -o /dev/null "$URL"
          done
